// falp_error.h -*-c++-*-
// FeliCa Ad-hoc Link Protocol Library
// Copyright 2006 Sony Corporation

// [CAUTION] This file is automatically generated. Do not edit this file.

#ifndef FALP_ERROR_H
#define FALP_ERROR_H

#if defined(__cplusplus)
enum enumeration_falp_error_type {
#else
typedef enum enumeration_falp_error_type_T {
#endif
    FALP_ERROR_NOT_OCCURRED = 2000,                    // エラーは発生していません (0x7d0)
    FALP_TIMEOUT = 2001,                               // タイムアウトしました (0x7d1)
    FALP_SHUTDOWN = 2002,                              // シャットダウンされています (0x7d2)
    FALP_HANDSHAKE_FAIL = 2003,                        // ハンドシェイクに失敗しました (0x7d3)
    FALP_PARAM_ERROR = 2004,                           // パラメータが不正です (0x7d4)
    FALP_MEMORY_ALLOCATION_ERROR = 2005,               // メモリの確保ができません (0x7d5)
    FALP_OUT_OF_RANGE = 2006,                          // 範囲外の値が指定されました (0x7d6)
    FALP_ILLEGAL_STATE_ERROR = 2007,                   // 状態が不正です (0x7d7)
    FALP_FELICA_COMMAND_TIMEOUT = 2008,                // FeliCaコマンドがタイムアウトしました (0x7d8)
    FALP_PACKET_FORMAT_ERROR = 2009,                   // パケットフォーマットが不正です (0x7d9)
    FALP_PORT_BUSY = 2010,                             // ポートビジーが発生しました (0x7da)
    FALP_RW_LIBRARY_ERROR = 2011,                      // FeliCaリーダ／ライタコントロールライブラリからエラーが返されました (0x7db)
    FALP_RW_RECEIVE_DATA_LENGTH_ERROR = 2012,          // 受信したデータの長さが異常です (0x7dc)
    FALP_RW_RECEIVE_DATA_CODE_ERROR = 2013,            // 受信したコードが異常です (0x7dd)
    FALP_RW_GET_ATTRIBUE_RATE_ERROR = 2014,            // リーダ／ライタから無線通信速度が正しく取得できませんでした (0x7de)
    FALP_FELICA_LIBRARY_NOT_INITIALIZED = 2015,        // FeliCaライブラリが初期化されていません (0x7df)
    FALP_LIBRARY_INITIALIZE_ERROR = 2016,              // FALPライブラリの初期化に失敗しました (0x7e0)
    FALP_READER_WRITER_NOT_OPENED = 2017,              // リーダ／ライタがオープンされていません (0x7e1)
    FALP_START_POLLING_STARTED = 2018,                 // START POLLING が稼働しているためFALPを開始できません (0x7e2)
    FALP_ALREADY_OPENED = 2019,                        // FALPモードに既に移行しています (0x7e3)
    FALP_NOT_OPEND = 2020,                             // FALPモードではありません (0x7e4)
    FALP_DEVICE_COMMUNICATION_ERROR = 2021,            // USB通信エラーが発生しているか、デバイスが存在しません(0x7e5)
    FALP_DEVICE_BUSY = 2022,                           // デバイスが他で使用されているか、アクセス権が獲得できません(0x7e6)
    FALP_DEVICE_COMMUNICATION_PARAMETER_ERROR = 2023,  // デバイスアクセス時のパラメータが不正です(0x7e7)
    FALP_FELICA_COMMAND_ERROR = 2024,                  // FeliCaコマンドレスポンスでエラーが通知されました(0x7e8)
    FALP_FELICA_THRU_ERROR = 2025,                     // Communicate Thruでエラーが通知されました(0x7e9)
    FALP_SYNTAX_ERROR = 2026,                          // シンタックスエラーが発生しました(0x7ea)
    FALP_COMMAND_CHECKSUM_ERROR = 2027,                // コマンドチェックサム(LCS,DCS)エラーが発生しました(0x7eb)
    FALP_COMMAND_IDTR_ERROR = 2028,                    // 不正なトランザクションIDが検出されました(0x7ec)
    FALP_READER_WRITER_MODE_ERROR = 2029,              // リーダ／ライタのモード状態によりコマンドが実行されませんでした(0x7ed)
    FALP_ILLEGAL_COMMAND_PACKET = 2030,                // コマンドのヘッダ・フッタ部が不正です(0x7ee)
    FALP_STATUS_FLAG_ERROR = 2031,                     // ステータスコードが正常・タイムアウト以外です(0x7ef)
    FALP_LOG_FILE_OPEN_ERROR = 2032,                   // FALPログファイルがオープンできません(0x7f0) 
    FALP_LOG_START_ERROR = 2033,                       // FALPログの取得開始に失敗しました(0x7f1)
    FALP_UNKNOWN_ERROR = 2034,                         // 原因不明のエラーが発生しました(0x7f2)
    FALP_USB_DRIVER_INTERNAL_ERROR = 2035,             // ドライバ内部エラーが発生しました(0x7f3)
    FALP_TARGET_NOT_FOUND = 2036,                      // ターゲットを捕捉することができませんでした(0x7f4)
	FALP_INITIATOR_IDLE_MODE = 2037,                   // FALP IDLEモードです(0x7f5)
	FALP_INITIATOR_TRANSMIT_MODE = 2038,               // FALP イニシエーター転送モードです(0x7f6)
	FALP_INITIATOR_TRANSMIT_END_MODE = 2039,           // FALP イニシエーター転送終了モードです(0x7f7)
	FALP_TARGET_TRANSMIT_MODE = 2040,                  // FALP ターゲット転送モードです(0x7f8)
	FALP_TARGET_TRANSMIT_END_MODE = 2041,              // FALP ターゲット転送終了モードです(0x7f9)
	FALP_CALL_BACK_PARAMETERS_NOT_SET = 2042,          // FALP ターゲット用コールバックパラメータが設定されていません(0x7fa)
	FALP_TARGET_WAIT_MODE = 2043,                      // すでにFALP ターゲット接続待ち要求が発行されています(0x7fb)
	FALP_NOT_TARGET_WAIT_MODE = 2044,                  // FALP ターゲット接続待ち要求を発行していません(0x7fc)
	FALP_MESSAGE_REGISTRATION_ERROR = 2045,            // FALP ターゲット接続通知メッセージの登録に失敗しました(0x7fd)
	FALP_NOT_TARGET_MODE = 2046,                       // FALP ターゲットモードではありません(0x7fe)
	FALP_CANNOT_START_TARGET_WAIT = 2047,              // FALP ターゲット接続待ちを開始できません(07ff)
	FALP_PROPOSE_TIMEOUT = 2048,                       // Propose Ad-hocの応答待ちでタイムアウトしました(0x800)
	FALP_MODE_TRANSMIT_ERROR = 2049,                   // モード移行のためのデバイス設定処理でエラーが発生しました(0x801)
	FALP_DEVICE_INITIALIZE_ERROR = 2050,               // デバイスの初期化でエラーが発生しました(0x802)
	FALP_TEMPERATURE_ERROR = 2051,                     // デバイスが温度異常です(0x803)
	FALP_TEMPERATURE_FATAL_ERROR = 2052,               // 温度異常によりデバイスが使用できない状態です(0x804)
	FALP_SYSTEM_BUSY = 2053                            // システムビジーが発生しました(0x805)

#if defined(__cplusplus)
};
#else
}enumeration_falp_error_type;
#endif


/*
2000 = エラーは発生していません
2001 = タイムアウトしました
2002 = シャットダウンされています
2003 = ハンドシェイクに失敗しました
2004 = パラメータが不正です
2005 = メモリの確保ができません
2006 = 範囲外の値が指定されました
2007 = 状態が不正です
2008 = FeliCaコマンドがタイムアウトしました
2009 = パケットフォーマットが不正です
2010 = ポートビジーが発生しました
2011 = FeliCaリーダ／ライタコントロールライブラリからエラーが返されました
2012 = 受信したデータの長さが異常です
2013 = 受信したコードが異常です
2014 = リーダ／ライタから無線通信速度が正しく取得できませんでした
2015 = FeliCaライブラリが初期化されていません
2016 = FALPライブラリの初期化に失敗しました
2017 = リーダ／ライタがオープンされていません
2018 = START POLLING が稼働しているためFALPを開始できません
2019 = FALPモードに既に移行しています
2020 = FALPモードではありません
2021 = USB通信エラーが発生しているか、デバイスが存在しません
2022 = デバイスが他で使用されているか、アクセス権が獲得できません
2023 = デバイスアクセス時のパラメータが不正です
2024 = FeliCaレスポンスでエラーが通知されました
2025 = Communicate Thruでエラーが通知されました
2026 = シンタックスエラーが発生しました
2027 = コマンドチェックサム(LCS,DCS)エラーが発生しました
2028 = 不正なトランザクションIDが検出されました
2029 = リーダ／ライタのモード状態によりコマンドが実行されませんでした
2030 = コマンドのヘッダ・フッタ部が不正です
2031 = ステータスコードが正常・タイムアウト以外です(0x7ef)
2032 = FALPログファイルがオープン出来ません 
2033 = FALPログの取得開始に失敗しました
2034 = 原因不明のエラーが発生しました
2035 = ドライバ内部エラーが発生しました
2036 = ターゲットを捕捉することができませんでした
2037 = FALP IDLEモードです
2038 = FALP イニシエーター転送モードです
2039 = FALP イニシエーター転送終了モードです
2040 = FALP ターゲット転送モードです
2041 = FALP ターゲット転送終了モードです
2042 = FALP ターゲット用コールバックパラメータが設定されていません
2043 = すでにFALP ターゲット接続待ち要求が発行されています
2044 = FALP ターゲット接続待ち要求を発行していません
2045 = FALP ターゲット接続通知メッセージの登録に失敗しました
2046 = FALP ターゲットモードではありません
2047 = FALP ターゲット接続待ちを開始できません
2048 = Propose Ad-hocの応答待ちでタイムアウトしました
2049 = モード移行のためのデバイス設定処理でエラーが発生しました
2050 = デバイスの初期化でエラーが発生しました
2051 = デバイスが温度異常です
2052 = 温度異常によりデバイスが使用できない状態です
2053 = システムビジーが発生しました
*/

#endif